<!DOCTYPE html>
<html lang="en">
<head>
    <?php require_once 'models/UserRepository.php'; // Incluimos UserRepository para obtener los nombres de autor ?>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>
    <?php if ($_SESSION['user']): ?>           
        <a href="index.php?c=blog&action=new">Añadir</a>
        <br><a href='index.php?c=register&logout=1'>Cerrar sesión</a>
    <?php endif; ?>

    <hr>

    <?php if (isset($posts) && is_array($posts) && count($posts) > 0): ?>
        <?php foreach($posts as $post): ?>
            <div style="border:1px solid #ccc; padding:10px; margin-bottom:10px;">
                <h2><?= $post->getTitle() ?></h2>
                <p><?= nl2br(htmlspecialchars($post->getText())) ?></p>
                <small>
                    Autor: <?= htmlspecialchars(UserRepository::getUserById($post->getAuthor())->getUsername()) ?> | Fecha: <?= $post->getDatetime() ?>
                </small>
                <br>
                <?php if ($_SESSION['user'] && ($_SESSION['user']->getRol() ==  1 || $_SESSION['user']->getId() == $post->getAuthor())): ?>
                    <a href="index.php?c=blog&action=delete&id=<?= $post->getId() ?>" style="color:red; font-size: 0.8em;">Borrar</a>
                <?php endif; ?>
                <br>
                    <a href="index.php?c=blog&id=<?= $post->getId() ?>">Ver</a>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p>No hay posts para mostrar.</p>
    <?php endif; ?>
</body>
</html>