<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Tema</title>
</head>
<body>
    <h1>New Tema</h1>
    <form action="index.php?c=foro" method="POST">
        <label for="title">Título:</label><br>
        <input type="text" id="title" name="title" placeholder="Título"><br><br>
        <label for="text">Texto:</label><br>
        <textarea id="text" name="text" placeholder="Escribe tu texto aquí..." rows="10" cols="80"></textarea><br><br>
        <input type="submit" value="Publicar">
    </form>
</body>
</html>