<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>
<body>
    <h1> Login </h1>
    
    <form action="index.php" method="POST">
            <input type="text" name="username" placeholder="nombre de usuario" />
            <input type="password" name="password" placeholder="contraseña" />
            <input type="submit" value="Entrar" />
            <a href="index.php?c=register&register=1">Registrarse</a>
    </form>    
    <?php 
        if (isset($message)) {
            echo "<p>" . $message . "</p>";
        }
    ?>
</body>
</html>