<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coments</title>
</head>
<body>
    <form action="index.php?c=blog" method="POST">
    <form action="index.php?c=blog&id=<?= htmlspecialchars($_GET['id']) ?>" method="POST">
        <label for="content">Comentario:</label><br>
        <textarea id="content" name="content" placeholder="Escribe tu comentario aquí..." rows="10" cols="80"></textarea><br><br>

        <input type="submit" value="Crear">
    </form>
</body>
</html>