<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Películas</h1>
    <?php

    foreach($movies as $movie){
        echo "<a href='index.php?c=movie&id=".$movie->getId()."'>" . $movie->getTitle() . "</a><br>";
    }

    if (!$_SESSION['user']) {  
     if($error) {
            echo "ERROR: " . $error;    
        }
    }
    else {
        echo "<br><a href='index.php?c=register&logout=1'>Cerrar sesión</a>";
    }


    ?>
</body>
</html>