<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Películas</title>
</head>
<body>
    <h1>Películas</h1>
    <?php foreach($movies as $movie): ?>
        <a href="index.php?c=movie&id=<?= $movie->getId() ?>"><?= htmlspecialchars($movie->getTitle()) ?></a>
        <?php if ($_SESSION['user']): ?>
            <a href="index.php?c=movie&action=delete&id=<?= $movie->getId() ?>" onclick="return confirm('¿Seguro que quieres borrar esta película?');">Borrar</a>
        <?php endif; ?>
        <br>
    <?php endforeach; ?>

    <?php if ($_SESSION['user']): ?>
        <a href="index.php?c=movie&action=new">Añadir</a>
        <br><a href='index.php?c=register&logout=1'>Cerrar sesión</a>
    <?php endif; ?>
</body>
</html>