<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
    if($info){
        echo "<script>alert('" .$info. "');</script>";
    }
    else{
        foreach($movies as $movie){
            if($movie->getId() == $_GET['id']){
                echo "<h1>" .$movie->getTitle(). "</h1>";
                echo "<p>" .$movie->getAuthor(). "</p>";
                echo "<p>" .$movie->getYear(). "</p>";
                echo "<p>" .$movie->getDescription(). "</p>";
                echo "<img src='posters/" .$movie->getPoster(). "' alt='" .$movie->getTitle(). " Poster' style='width:200px;'><br>";
                echo "<br><a href='index.php'>Volver a la lista de películas</a>";
            }
        }
    
    }
?>
</body>
</html>