<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Crear película</h2>
    <form action="index.php?c=movie" method="POST" enctype="multipart/form-data">
        <input type="text" name="title" placeholder="title">
        <input type="file" name="poster" placeholder="poster">
        <input type="text" name="author" placeholder="author">
        <input type="text" name="year" placeholder="year">
        <input type="text" name="description" placeholder="description">
        <input type="submit" value="Crear">
    </form>
    <br><a href="index.php">Volver al listado</a>
</body>
</html>