<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Registro </h1>
    
    <form action="index.php?c=register" method="POST">
            <input type="text" name="username" placeholder="nombre de usuario" />
            <input type="password" name="password" placeholder="contraseña" />
            <input type="submit" name="register" value="Entrar" />
    </form>

</body>
</html>