<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New product view</title>
</head>
<body>
    <h1> Nuevo producto </h1>

    <form action="index.php?c=shop&action=add" method="POST" enctype="multipart/form-data">
            <input type="text" name="name" placeholder="Nombre del producto" />
            <input type="text" name="description" placeholder="Descripción del producto" />
            <input type="number" name="stock" placeholder="Stock" />
            <input type="number" step="0.01" name="price" placeholder="Precio" />
            <input type="file" name="productPicture" placeholder="Foto del producto" />
            <input type="submit" name="addProduct" value="Agregar producto" />
    </form>

    <?php
        if(isset($message)){
            echo "<p>" . $message . "</p>";
        }
    ?>
    
</body>
</html>